"boom": true,
"configue": true,
"dogwater": false,
"glue": true,
"good": true,
"good-console": "^6.1.2",
"good-squeeze": "^4.0.0",
"hapi": "^14.1.0",
"hapi-authorization": "^3.0.2",
"hapi-boom-decorators": "^2.0.0",
"hapi-named-routes": "^0.3.0",
"haute-couture": "^1.2.0",
"hoek": "^4.0.2",
"inert": "^4.0.1",
"nconf": "^0.8.4",
"nconf-yaml": "^1.0.2",
"poop": "^2.0.2",
"sails-disk": "^0.10.10",
"sails-memory": "^0.10.7",
"sails-mongo": "^0.12.1",
"sails-mysql": "^0.11.5",
"sails-postgresql": "^0.11.4",
"uhu": "^1.0.0",
"vision": "^4.1.0",
"waterline": "
